AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-rest-api

  Sample SAM Template for aws-sam-rest-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  MovieApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: movie-api/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          DYNAMODB_LOCAL_ENDPOINT: 'http://192.168.1.3:8002'
      Events:
        List:
          Type: Api
          Properties:
            Path: /movies
            Method: get
        Create:
          Type: Api
          Properties:
            Path: /movies/create
            Method: post
        Destroy:
          Type: Api
          Properties:
            Path: /movies/{id}/delete
            Method: delete

Outputs:
  MovieApi:
    Description: "API Gateway endpoint URL for Prod stage for Movie API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/"
  MovieApiFunction:
    Description: "Movie API Lambda Function ARN"
    Value: !GetAtt MovieApiFunction.Arn
  MovieApiFunctionIamRole:
    Description: "Implicit IAM Role created for Movie API function"
    Value: !GetAtt MovieApiFunctionRole.Arn
